version: '3.1'

services:
  dbt:
    image: mysql
    restart: always
    container_name: dbt
    ports:
      - "3306:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysql
      MYSQL_DATABASE: "dbt"
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin