version: '3.1'

services:
  db:
    image: mysql
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysql
      MYSQL_DATABASE: "db"
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin